export const dobValidationConstants = {
  INVALID_DAY: "INVALID_DAY",
  INVALID_MONTH: "INVALID_MONTH",
  INVALID_YEAR: "INVALID_YEAR",
  INVALID_DATE: "INVALID_DATE",
  INVALID_AGE: "INVALID_AGE",
};
