parameters:
  - name: environment
    type: string
  - name: functionAppName
    type: string
  - name: azureSubscription
    type: string
  - name: resourceGroupName
    type: string
  - name: keyVaultName
    type: string
  - name: slotName
    type: string


steps:
  - task: AzureAppServiceSettings@1
    displayName: 'Configure Function App Settings'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appName: ${{ parameters.functionAppName }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      slotName: ${{ parameters.slotName }}
      appSettings: |
        [
          {
            "name": "FUNCTIONS_EXTENSION_VERSION",
            "value": "~4",
            "slotSetting": false
          },
          {
            "name": "FUNCTIONS_WORKER_RUNTIME",
            "value": "dotnet-isolated",
            "slotSetting": false
          },
          {
            "name": "DOTNET_FRAMEWORK_VERSION",
            "value": "v8.0",
            "slotSetting": false
          },
          {
            "name": "KeyVaultUri",
            "value": "https://${{ parameters.keyVaultName }}.vault.azure.net/",
            "slotSetting": false
          },
          {
            "name": "WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED",
            "value": "1",
            "slotSetting": false
          },
          {
            "name": "WEBSITE_RUN_FROM_PACKAGE",
            "value": "1",
            "slotSetting": false
          }